env:
   global:
     - CONAN_USERNAME: "filigreetech"
     - CONAN_LOGIN_USERNAME: "filigreeconanbot"
     - CONAN_CHANNEL: "testing"
     - CONAN_UPLOAD: "https://api.bintray.com/conan/filigreetech/conan-pkg"
     - CONAN_ARCHS: "x86_64"

linux: &linux
   os: linux
   sudo: required
   language: python
   python: "2.7"
   services:
     - docker
osx: &osx
   os: osx
   language: generic
matrix:
   include:
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=6.0 CONAN_DOCKER_IMAGE=conanio/clang60

      - <<: *linux
        env: CONAN_CLANG_VERSIONS=7.0 CONAN_DOCKER_IMAGE=conanio/clang7

      - <<: *osx
        osx_image: xcode10
        env: CONAN_APPLE_CLANG_VERSIONS=10.0

install:
  - chmod +x .ci/travis/install.sh
  - ./.ci/travis/install.sh

script:
  - chmod +x .ci/travis/run.sh
  - ./.ci/travis/run.sh
